### Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

### Load and Inspect Data

In [ ]:
# Read data
df = pd.read_csv(r"/home/ceejay/Documents/Code/Robotics/practice-ai/datasets/messy_dataset_50.csv")

# Create a copy to work on
df_copy = df.copy()

In [5]:
# View first five row
df_copy.head()

   ID     Name     Age             Email   Join_Date  Salary Department
0   1    Grace      57    grace@mail.com  18-08-2022  55,000      Admin
1   2      Bob  twenty  invalidemail.com         NaN  49,000         IT
2   3    frank      34               NaN  16-02-2020  69,000      Admin
3   4  Isabel      NaN   isabel@mail.com  08-10-2020     NaN         it
4   5     davi      31         davi@mail  2022-12-20   78828  Marketing

In [6]:
# View last five row
df_copy.tail()

,ID,Name,Age,Email,Join_Date,Salary,Department
45,46,Henry,29 years,NaN,NaN,53454,finance
46,47,Alice,thirty,alice@@mail.com,NaN,NaN,Finance
47,48,Charle,46,invalidemail.com,not_a_date,sixty thousand,hr
48,49,David,27 years,invalidemail.com,not_a_date,34431,Admin
49,50,Grace,59,grace@mail,2023-05-21,60245,NaN

In [8]:
# Check shape
df_copy.shape

(50, 7)

In [9]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          50 non-null     int64
 1   Name        50 non-null     str
 2   Age         45 non-null     str
 3   Email       37 non-null     str
 4   Join_Date   31 non-null     str
 5   Salary      30 non-null     str
 6   Department  39 non-null     str
dtypes: int64(1), str(6)
memory usage: 2.9 KB

In [10]:
df_copy.describe()

             ID
count  50.00000
mean   25.50000
std    14.57738
min     1.00000
25%    13.25000
50%    25.50000
75%    37.75000
max    50.00000

In [11]:
df_copy.describe(include="all")

,ID,Name,Age,Email,Join_Date,Salary,Department
count,50.00000,50,45,37,31,30,39
unique,NaN,27,33,23,27,19,14
top,NaN,Grace,57,invalidemail.com,not_a_date,sixty thousand,Admin
freq,NaN,7,3,8,5,12,7
mean,25.50000,NaN,NaN,NaN,NaN,NaN,NaN
std,14.57738,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN
25%,13.25000,NaN,NaN,NaN,NaN,NaN,NaN
50%,25.50000,NaN,NaN,NaN,NaN,NaN,NaN
75%,37.75000,NaN,NaN,NaN,NaN,NaN,NaN
max,50.00000,NaN,NaN,NaN,NaN,NaN,NaN

### Clean Data

* Age - text to number conversion

In [12]:
# Check unique values in age column
df_copy["Age"].unique()

<StringArray>
[      '57',   'twenty',       '34',        nan,       '31', '60 years',
       '60',       '58', '50 years', '53 years', '43 years',   'thirty',
       '55',       '40',       '54',       '56',       '21', '45 years',
 '49 years', '22 years', '38 years', '30 years', '41 years',       '38',
       '20', '42 years', '36 years',       '36', '28 years', '26 years',
 '29 years',       '46', '27 years',       '59']
Length: 34, dtype: str

In [13]:
# Change "twenty", "thirty" to 20 and 30 respectivelu
df_copy["Age"] = df_copy["Age"].str.replace("twenty", "20")
df_copy["Age"] = df_copy["Age"].str.replace("thirty", "30")

In [14]:
# Remove "years" at the back of the age
df_copy["Age"] = df_copy["Age"].str.replace("years", "", regex=False)

In [15]:
# Let's see unique value again
df_copy["Age"].unique()

<StringArray>
[ '57',  '20',  '34',   nan,  '31', '60 ',  '60',  '58', '50 ', '53 ', '43 ',
  '30',  '55',  '40',  '54',  '56',  '21', '45 ', '49 ', '22 ', '38 ', '30 ',
 '41 ',  '38', '42 ', '36 ',  '36', '28 ', '26 ', '29 ',  '46', '27 ',  '59']
Length: 33, dtype: str

* Salary text conversion

In [16]:
df_copy["Salary"].unique()

<StringArray>
[        '55,000',         '49,000',         '69,000',              nan,
          '78828', 'sixty thousand',         '44,000',          '33033',
          '42606',         '76,000',          '79209',          '61050',
         '60,000',          '36890',          '76284',         '59,000',
         '41,000',          '53454',          '34431',          '60245']
Length: 20, dtype: str

In [17]:
# change "sixty thousand" to "60,000"
df_copy["Salary"] = df_copy["Salary"].str.replace("sixty thousand", "60,000")

In [18]:
df_copy["Salary"].unique()

<StringArray>
['55,000', '49,000', '69,000',      nan,  '78828', '60,000', '44,000',
  '33033',  '42606', '76,000',  '79209',  '61050',  '36890',  '76284',
 '59,000', '41,000',  '53454',  '34431',  '60245']
Length: 19, dtype: str

In [19]:
# View data
df_copy.head()

   ID     Name  Age             Email   Join_Date  Salary Department
0   1    Grace   57    grace@mail.com  18-08-2022  55,000      Admin
1   2      Bob   20  invalidemail.com         NaN  49,000         IT
2   3    frank   34               NaN  16-02-2020  69,000      Admin
3   4  Isabel   NaN   isabel@mail.com  08-10-2020     NaN         it
4   5     davi   31         davi@mail  2022-12-20   78828  Marketing

#### Format Inconsistencies