In [1]:
import pandas as pd

#### Pandas Series

In [2]:
# In Pandas, a `Series` is a one-dimensional labeled array that can hold data of any type. A series is just like a single column of a table.

# Using python list to create a pandas series
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Creating the series with .series()
series = pd.Series(data)

print(series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [5]:
# Creating series with personalized index
series2 = pd.Series(data, index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

series2.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
# Or we could use a dictionary for personalized index
data_dict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6}

series3 = pd.Series(data_dict)
print(series3)

print(type(series3))

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64
<class 'pandas.Series'>

### Dataframe

In [16]:
# In Pandas, a DataFrame is a two-dimensional labeled array that can hold data of any type into rows and columns.

my_data = {
    "Name": ["John", "Bright", "Rachael", "Janet", "Pedro", "Destine", "Ronaldo"],
    "Age": [20, 22, 18, 12, 19, 29, 33],
    "Country": ["Nigeria", "Ghana", "England", "Spain", "Liberia", "Senegal", "Italy"]
}

# Use .DataFrame()
df = pd.DataFrame(my_data)

# View the dataframe
df

      Name  Age  Country
0     John   20  Nigeria
1   Bright   22    Ghana
2  Rachael   18  England
3    Janet   12    Spain
4    Pedro   19  Liberia
5  Destine   29  Senegal
6  Ronaldo   33    Italy

In [13]:
# We can also have a dataframe with list of dictionaries
my_data = [
    {"Name": "Michael", "Age": 15, "Country": "USA"},
    {'Name': "Joe", 'Age': 10, "Country": "South Africa"},
    {'Name': 'Victory', 'Age': 20, "Country": "Nigeria"}
]

# Let's define the dataframe
df2 = pd.DataFrame(my_data)

# View the dataframe
df2

      Name  Age       Country
0  Michael   15           USA
1      Joe   10  South Africa
2  Victory   20       Nigeria

In [18]:
# Using lists to create dataframes
food = [
    ["Rice", "Carbohydrate", 50],
    ["Yoghurt", "Protein", 15],
    ["Pizza", "Carbohydrate", 10],
    ["Beef", "Protein", 12]
]

food_df = pd.DataFrame(food, columns=["Food", "Food Class", "Price"])

food_df

      Food    Food Class  Price
0     Rice  Carbohydrate     50
1  Yoghurt       Protein     15
2    Pizza  Carbohydrate     10
3     Beef       Protein     12

In [19]:
food_df2 = pd.DataFrame(food, columns=["Food", "Food Class", "Price"], index=["a", "b", "c", "d"])

food_df2

      Food    Food Class  Price
a     Rice  Carbohydrate     50
b  Yoghurt       Protein     15
c    Pizza  Carbohydrate     10
d     Beef       Protein     12